#!/bin/sh

set -e

[ -x /usr/local/bin/docker-run-pre ] && /usr/local/bin/docker-run-pre

docker-bootstrap

if [ -x /usr/local/bin/docker-run-post ]; then
	exec /bin/sh usr/local/bin/docker-run-post
else
	exec s6-svscan /usr/local/etc/s6
fi

