#!/bin/sh

set -e

[ -x /usr/local/bin/docker-run-pre ] && /usr/local/bin/docker-run-pre

docker-bootstrap

if [ -x /usr/local/bin/docker-run-alt ]; then
	exec /bin/sh /usr/local/bin/docker-run-alt
else
	exec s6-svscan /usr/local/etc/s6
fi

